---
- name: Installing docker-engineeeeee
  raw: yum-config-manager --add-repo  https://docs.docker.com/engine/installation/linux/repo_files/centos/docker.repo 
 
- name: Adding the user to the Docker group
  user:
    name: ec2-user
    groups: docker
 
- name: Installing the docker-engine
  yum: name=docker-engine state=present
