---
# tasks file for docker
- name: Fecting the code name
  command: /usr/bin/lsb_release -cs
  register: code
-  setfact: code_name=code
- debug: code_name=code

- name: Adding the docker repository  to /etc/apt/sources.list
  apt_repository:  
    repo: deb http://apt.dockerproject.org/repo/debian-{{code_name}} main
    state: present
